name: Enforce Approvals Before Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR approvals
        uses: hmarr/auto-approve-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the list of approved reviewers
          APPROVALS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews --jq '[.[] | select(.state=="APPROVED") | .user.login]')
          
          echo "Approvals: $APPROVALS"

          # Check if at least one company member has approved
          COMPANY_MEMBERS=("user1" "user2" "user3") # Replace with actual GitHub usernames
          COMPANY_APPROVED=false
          
          for user in "${COMPANY_MEMBERS[@]}"; do
            if echo "$APPROVALS" | grep -q "$user"; then
              COMPANY_APPROVED=true
              break
            fi
          done

          # Check if Yasmine has approved
          if echo "$APPROVALS" | grep -q "Yasmine"; then
            YASMINE_APPROVED=true
          else
            YASMINE_APPROVED=false
          fi

          if [ "$COMPANY_APPROVED" = false ]; then
            echo "❌ At least one company member must approve."
            exit 1
          fi

          if [ "$YASMINE_APPROVED" = false ]; then
            echo "❌ Yasmine must approve before merging."
            exit 1
          fi

          echo "✅ PR meets approval requirements!"
